version: '3'
services:
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        ports:
          - "3001:3001"
    frontend:
        build:
          dockerfile: Dockerfile
          context: ./frontend
        ports:
          - "3000:80"